deploy:
	make --directory=mettalex-balancer deploy_pool_factory
	make --directory=mettalex-balancer deploy_balancer_amm
	make --directory=mettalex-coin deploy
	make --directory=mettalex-vault deploy_long
	make --directory=mettalex-vault deploy_short
	make --directory=mettalex-vault deploy_vault
	make --directory=mettalex-yearn deploy_controller
	make --directory=mettalex-yearn deploy_vault

