build: contracts/StrategyBalancerMettalex.sol
	npx oz compile

init:
	npm init -y
	npm install @openzeppelin/cli
	npm install @openzeppelin/contracts-ethereum-package@2.5
	npm audit fix
	npx oz init pool-controller --no-interactive